spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
#    show-sql: true
logging.level:
  org.hibernate:
    SQL: debug
    type: trace
#    type.descriptor: trace
